version: 2.1

executors:
  app-executor:
    docker:
      - image: circleci/node:lts
    working_directory: ~/repo

commands:
  build:
    description: "Builds the project"
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            - v1-dependencies-
      - run:
          name: Install Dependencies
          command: |
            unset CI
            yarn install
      - save_cache:
          key: v1-dependencies-{{ checksum "package.json" }}
          paths:
            - ./node_modules
      - run:
          name: Build for current environment.
          command: CI=false yarn build
  deploy:
    description: "Deploy"
    steps:
      - run:
          name: Firebase Deploy
          command: |
            yarn add firebase-tools
            yarn run firebase deploy --token=$FIREBASE_TOKEN --project bacoor-swap
jobs:
  build-deploy:
    executor: app-executor
    steps:
      - build
      - deploy

workflows:
  version: 2
  production:
    jobs:
      - build-deploy:
          filters:
            branches:
              only: ci